"""schema sync pre-bookings-rename

Revision ID: 034068119d61
Revises: add_properties_simple
Create Date: 2025-10-08 07:17:50.144298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034068119d61'
down_revision: Union[str, Sequence[str], None] = 'add_properties_simple'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_articles_created_at', 'articles', ['created_at'], unique=False)
    op.create_index('idx_articles_slug', 'articles', ['slug'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('from_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('handover_quarter', sa.String(length=20), nullable=True),
    sa.Column('bedrooms_min', sa.Integer(), nullable=True),
    sa.Column('bedrooms_max', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('payment_plan', sa.String(length=1000), nullable=True),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_created_at', 'projects', ['created_at'], unique=False)
    op.create_index('ix_projects_developer_id', 'projects', ['developer_id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('st_listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Float(), nullable=True),
    sa.Column('nightly_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cleaning_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('service_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('security_deposit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('cancellation_policy', sa.String(length=20), nullable=False),
    sa.Column('instant_book', sa.Boolean(), nullable=False),
    sa.Column('min_nights', sa.Integer(), nullable=True),
    sa.Column('max_nights', sa.Integer(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_st_listings_area_id', 'st_listings', ['area_id'], unique=False)
    op.create_index('ix_st_listings_county', 'st_listings', ['county'], unique=False)
    op.create_index('ix_st_listings_county_town', 'st_listings', ['county', 'town'], unique=False)
    op.create_index('ix_st_listings_created_at', 'st_listings', ['created_at'], unique=False)
    op.create_index('ix_st_listings_host_id', 'st_listings', ['host_id'], unique=False)
    op.create_index('ix_st_listings_town', 'st_listings', ['town'], unique=False)
    op.create_table('st_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('price_override', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_nights_override', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['st_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_st_availability_listing_date', 'st_availability', ['listing_id', 'date'], unique=True)
    op.create_table('st_bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_auth_id', sa.String(length=100), nullable=True),
    sa.Column('payment_capture_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['listing_id'], ['st_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_st_bookings_guest_id', 'st_bookings', ['guest_id'], unique=False)
    op.create_index('ix_st_bookings_listing_id', 'st_bookings', ['listing_id'], unique=False)
    op.create_index('ix_st_bookings_status', 'st_bookings', ['status'], unique=False)
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'property_id')
    )
    op.create_index('idx_favorite_created_at', 'favorites', ['created_at'], unique=False)
    op.create_index('idx_favorite_property_id', 'favorites', ['property_id'], unique=False)
    op.create_index('idx_favorite_user_id', 'favorites', ['user_id'], unique=False)
    op.create_table('property_status_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_property_status_log_created_at', 'property_status_logs', ['created_at'], unique=False)
    op.create_index('idx_property_status_log_property_id', 'property_status_logs', ['property_id'], unique=False)
    op.create_table('st_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['st_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_st_messages_booking_id', 'st_messages', ['booking_id'], unique=False)
    op.create_table('st_payouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['st_bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_st_payouts_host_id', 'st_payouts', ['host_id'], unique=False)
    op.create_index('ix_st_payouts_status', 'st_payouts', ['status'], unique=False)
    op.create_table('st_tax_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['st_bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_areas_slug', 'areas', ['slug'], unique=False)
    op.create_index(op.f('ix_bundle_bookings_id'), 'bundle_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bundled_items_id'), 'bundled_items', ['id'], unique=False)
    op.create_index(op.f('ix_bundles_id'), 'bundles', ['id'], unique=False)
    op.create_index(op.f('ix_car_rentals_id'), 'car_rentals', ['id'], unique=False)
    op.create_index(op.f('ix_car_rentals_renter_id'), 'car_rentals', ['renter_id'], unique=False)
    op.create_index(op.f('ix_developers_slug'), 'developers', ['slug'], unique=True)
    op.create_index('ix_nav_product_date', 'inv_nav_snapshots', ['product_id', 'nav_date'], unique=True)
    op.create_index('ix_orders_product_id', 'inv_orders', ['product_id'], unique=False)
    op.create_index('ix_orders_status', 'inv_orders', ['status'], unique=False)
    op.create_index('ix_orders_user_id', 'inv_orders', ['user_id'], unique=False)
    op.create_index('ix_positions_product_id', 'inv_positions', ['product_id'], unique=False)
    op.create_index('ix_positions_user_id', 'inv_positions', ['user_id'], unique=False)
    op.create_index(op.f('ix_inv_products_slug'), 'inv_products', ['slug'], unique=True)
    op.create_index('idx_media_property_id', 'media', ['property_id'], unique=False)
    op.alter_column('properties', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('properties', 'property_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('properties', 'address',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('properties', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('properties', 'longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('properties', 'square_footage',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('properties', 'slug',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=250),
               nullable=False)
    op.alter_column('properties', 'meta_description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=160),
               existing_nullable=True)
    op.alter_column('properties', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_properties_agent_id', 'properties', ['agent_id'], unique=False)
    op.create_index('ix_properties_created_at', 'properties', ['created_at'], unique=False)
    op.create_index('ix_properties_property_type_id', 'properties', ['property_type_id'], unique=False)
    op.create_index('ix_properties_slug', 'properties', ['slug'], unique=False)
    op.create_index('ix_properties_status', 'properties', ['status'], unique=False)
    op.create_unique_constraint(None, 'properties', ['slug'])
    op.create_foreign_key(None, 'properties', 'users', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'properties', 'property_types', ['property_type_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'properties', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_property_details_key', 'property_details', ['key'], unique=False)
    op.create_index('idx_property_details_property_id', 'property_details', ['property_id'], unique=False)
    op.create_index('idx_property_type_name', 'property_types', ['name'], unique=False)
    op.create_index(op.f('ix_tour_bookings_customer_id'), 'tour_bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tour_bookings_id'), 'tour_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_tours_id'), 'tours', ['id'], unique=False)
    op.create_index(op.f('ix_tours_operator_id'), 'tours', ['operator_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_owner_id'), 'vehicles', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_owner_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_tours_operator_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_id'), table_name='tours')
    op.drop_index(op.f('ix_tour_bookings_id'), table_name='tour_bookings')
    op.drop_index(op.f('ix_tour_bookings_customer_id'), table_name='tour_bookings')
    op.drop_index('idx_property_type_name', table_name='property_types')
    op.drop_index('idx_property_details_property_id', table_name='property_details')
    op.drop_index('idx_property_details_key', table_name='property_details')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='unique')
    op.drop_index('ix_properties_status', table_name='properties')
    op.drop_index('ix_properties_slug', table_name='properties')
    op.drop_index('ix_properties_property_type_id', table_name='properties')
    op.drop_index('ix_properties_created_at', table_name='properties')
    op.drop_index('ix_properties_agent_id', table_name='properties')
    op.alter_column('properties', 'agent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('properties', 'meta_description',
               existing_type=sa.String(length=160),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('properties', 'slug',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('properties', 'square_footage',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('properties', 'longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=11, scale=8),
               existing_nullable=True)
    op.alter_column('properties', 'latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
    op.alter_column('properties', 'address',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('properties', 'property_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('properties', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index('idx_media_property_id', table_name='media')
    op.drop_index(op.f('ix_inv_products_slug'), table_name='inv_products')
    op.drop_index('ix_positions_user_id', table_name='inv_positions')
    op.drop_index('ix_positions_product_id', table_name='inv_positions')
    op.drop_index('ix_orders_user_id', table_name='inv_orders')
    op.drop_index('ix_orders_status', table_name='inv_orders')
    op.drop_index('ix_orders_product_id', table_name='inv_orders')
    op.drop_index('ix_nav_product_date', table_name='inv_nav_snapshots')
    op.drop_index(op.f('ix_developers_slug'), table_name='developers')
    op.drop_index(op.f('ix_car_rentals_renter_id'), table_name='car_rentals')
    op.drop_index(op.f('ix_car_rentals_id'), table_name='car_rentals')
    op.drop_index(op.f('ix_bundles_id'), table_name='bundles')
    op.drop_index(op.f('ix_bundled_items_id'), table_name='bundled_items')
    op.drop_index(op.f('ix_bundle_bookings_id'), table_name='bundle_bookings')
    op.drop_index('ix_areas_slug', table_name='areas')
    op.drop_table('st_tax_records')
    op.drop_index('ix_st_payouts_status', table_name='st_payouts')
    op.drop_index('ix_st_payouts_host_id', table_name='st_payouts')
    op.drop_table('st_payouts')
    op.drop_index('ix_st_messages_booking_id', table_name='st_messages')
    op.drop_table('st_messages')
    op.drop_index('idx_property_status_log_property_id', table_name='property_status_logs')
    op.drop_index('idx_property_status_log_created_at', table_name='property_status_logs')
    op.drop_table('property_status_logs')
    op.drop_index('idx_favorite_user_id', table_name='favorites')
    op.drop_index('idx_favorite_property_id', table_name='favorites')
    op.drop_index('idx_favorite_created_at', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('ix_st_bookings_status', table_name='st_bookings')
    op.drop_index('ix_st_bookings_listing_id', table_name='st_bookings')
    op.drop_index('ix_st_bookings_guest_id', table_name='st_bookings')
    op.drop_table('st_bookings')
    op.drop_index('ix_st_availability_listing_date', table_name='st_availability')
    op.drop_table('st_availability')
    op.drop_index('ix_st_listings_town', table_name='st_listings')
    op.drop_index('ix_st_listings_host_id', table_name='st_listings')
    op.drop_index('ix_st_listings_created_at', table_name='st_listings')
    op.drop_index('ix_st_listings_county_town', table_name='st_listings')
    op.drop_index('ix_st_listings_county', table_name='st_listings')
    op.drop_index('ix_st_listings_area_id', table_name='st_listings')
    op.drop_table('st_listings')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index('ix_projects_developer_id', table_name='projects')
    op.drop_index('ix_projects_created_at', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_articles_slug', table_name='articles')
    op.drop_index('idx_articles_created_at', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
